version: '3.9'

services:
  argusscope:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/argusdb
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - mongodb
      - elasticsearch
    command: uvicorn argus_scope.api.server:app --host 0.0.0.0 --port 8000

  mongodb:
    image: mongo:8.0
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: elasticsearch:8.18.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  mongodb_data:
  elasticsearch_data:
