services:
  # سرویس اصلی برای اجرا در محیط توسعه و نهایی
  argusscope:
    build:
      context: .
      target: production  # به داکر می‌گوییم که لایه production را بسازد
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/argusdb
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - mongodb
      - elasticsearch
    command: poetry run uvicorn argus_scope.api.server:app --host 0.0.0.0 --port 8000 --reload

  # سرویس جدید، فقط برای اجرای تست‌ها
  tests:
    build:
      context: .
      target: test  # به داکر می‌گوییم که لایه test را بسازد
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/argusdb_test # استفاده از دیتابیس جدا برای تست
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - mongodb
      - elasticsearch
    command: ["poetry", "run", "pytest"]

  mongodb:
    image: mongo:8.0
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: elasticsearch:8.18.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/data/db

volumes:
  mongodb_data: